from __future__ import annotations
from typing import Protocol, Union
import pint

NumberOrQty = Union[float, int, pint.Quantity]

class FluidBackend(Protocol):
    """Backend interface in *SI floats only*."""
    fluid_id: str

    def T_crit(self) -> float: ...
    def p_crit(self) -> float: ...

    def p_sat(self, T_K: float) -> float: ...
    def T_sat(self, P_Pa: float) -> float: ...

    def s_sat_liq(self, P_Pa: float) -> float: ...
    def s_sat_vap(self, P_Pa: float) -> float: ...
    def s_fg(self, P_Pa: float) -> float: ...

    def h_sat_liq(self, P_Pa: float) -> float: ...
    def h_sat_vap(self, P_Pa: float) -> float: ...
    def h_fg(self, P_Pa: float) -> float: ...

    def p_vap(self, T_K: float) -> float: ...

    def s(self, T_K: float, P_Pa: float) -> float: ...
    def h(self, T_K: float, P_Pa: float) -> float: ...
    def rho(self, T_K: float, P_Pa: float) -> float: ...
    def mu(self, T_K: float, P_Pa: float) -> float: ...

    def rho_sat_liq(self, P_Pa: float) -> float: ...
    def rho_sat_vap(self, P_Pa: float) -> float: ...

    def cp(self, T_K: float, P_Pa: float) -> float: ...
    def cv(self, T_K: float, P_Pa: float) -> float: ...



class FluidAPI(Protocol):
    """User-facing API: accepts/returns pint.Quantity by default."""
    fluid_id: str

    def T_crit(self): ...
    def p_crit(self): ...

    def p_sat(self, T: NumberOrQty): ...
    def T_sat(self, P: NumberOrQty): ...

    def s_sat_liq(self, P: NumberOrQty): ...
    def s_sat_vap(self, P: NumberOrQty): ...
    def s_fg(self, P: NumberOrQty): ...

    def h_sat_liq(self, P: NumberOrQty): ...
    def h_sat_vap(self, P: NumberOrQty): ...
    def h_fg(self, P: NumberOrQty): ...

    def p_vap(self, T: NumberOrQty): ...

    def s(self, T: NumberOrQty, P: NumberOrQty): ...
    def h(self, T: NumberOrQty, P: NumberOrQty): ...
    def rho(self, T: NumberOrQty, P: NumberOrQty): ...
    def mu(self, T: NumberOrQty, P: NumberOrQty): ...

    def rho_sat_liq(self, P: NumberOrQty): ...
    def rho_sat_vap(self, P: NumberOrQty): ...

    def cp(self, T: NumberOrQty, P: NumberOrQty): ...
    def cv(self, T: NumberOrQty, P: NumberOrQty): ...
